services:
  vk_api_service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - spring.application.name=VK_API_service
      - server.port=8081
      - app.vk.api.url=https://api.vk.com/method
      - app.vk.api.version=5.199
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main_db:5432/main_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - vk_network
    depends_on:
      - main_db

  main_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  vk_network:
    driver: bridge

volumes:
  pg_data: